name: Deploy
permissions:
  contents: write
on:
  push:
    branches:
      - main # replace with your default branch name

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Clear cache
        run: rm -rf node_modules/.vite
      - name: Install dependencies
        run: npm i
      - name: Build
        run: npm run build
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          user_name: Mayank Singh Kushwah
          user_email: msrajawat298@gmail.com
