name: Deploy
permissions:
  contents: write
on:
  push:
    branches:
      - main # replace with your default branch name

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' # Adjust based on your local Node.js version
          cache: 'npm'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          if [ -f package-lock.json ]; then
            npm ci
          else
            npm install
          fi
      # Debug: List files and directories
      - name: List project files
        run: ls -R src/components

      # Debug: Check Node.js and npm versions
      - name: Check versions
        run: |
          node -v
          npm -v
      # Step 4: Build the project
      - name: Build
        run: npm run build
      # Step 5: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          user_name: "Mayank Singh Kushwah"
          user_email: msrajawat298@gmail.com
